// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaNominaMVC.Data;

#nullable disable

namespace SistemaNominaMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaNominaMVC.Models.Department", b =>
                {
                    b.Property<string>("dept_no")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("dept_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("dept_no");

                    b.HasIndex("dept_name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.DeptEmp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("dept_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("emp_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("to_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("dept_no");

                    b.HasIndex("emp_no");

                    b.ToTable("DeptEmps");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.DeptManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("dept_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("emp_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("to_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("dept_no");

                    b.HasIndex("emp_no");

                    b.ToTable("DeptManagers");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.Employee", b =>
                {
                    b.Property<int>("emp_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("emp_no"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ci")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("hire_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("emp_no");

                    b.HasIndex("ci")
                        .IsUnique();

                    b.HasIndex("correo")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.LogAuditoriaSalario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleCambio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("emp_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("emp_no");

                    b.ToTable("LogAuditoriaSalarios");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("emp_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("to_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("emp_no");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("emp_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("to_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("emp_no");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("emp_no")
                        .HasColumnType("int");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("emp_no")
                        .IsUnique();

                    b.HasIndex("usuario")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.DeptEmp", b =>
                {
                    b.HasOne("SistemaNominaMVC.Models.Department", "Department")
                        .WithMany("DeptEmps")
                        .HasForeignKey("dept_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaNominaMVC.Models.Employee", "Employee")
                        .WithMany("DeptEmps")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.DeptManager", b =>
                {
                    b.HasOne("SistemaNominaMVC.Models.Department", "Department")
                        .WithMany("DeptManagers")
                        .HasForeignKey("dept_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaNominaMVC.Models.Employee", "Employee")
                        .WithMany("DeptManagers")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.LogAuditoriaSalario", b =>
                {
                    b.HasOne("SistemaNominaMVC.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.Salary", b =>
                {
                    b.HasOne("SistemaNominaMVC.Models.Employee", "Employee")
                        .WithMany("Salaries")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.Title", b =>
                {
                    b.HasOne("SistemaNominaMVC.Models.Employee", "Employee")
                        .WithMany("Titles")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.User", b =>
                {
                    b.HasOne("SistemaNominaMVC.Models.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("SistemaNominaMVC.Models.User", "emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.Department", b =>
                {
                    b.Navigation("DeptEmps");

                    b.Navigation("DeptManagers");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.Employee", b =>
                {
                    b.Navigation("DeptEmps");

                    b.Navigation("DeptManagers");

                    b.Navigation("Salaries");

                    b.Navigation("Titles");

                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
